=== 2526dustinpicon-hash/LMSGI_DTD/dtd2.dtd
<!ELEMENT cataleg (llista_actors, llista_pelicules, llista_recomanacions_pelicules)>

<!-- llista d'actors -->
<!ELEMENT llista_actors (actor+)>
<!ELEMENT actor (nom, edat?)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT edat (#PCDATA)>
<!ATTLIST actor id ID #REQUIRED>

<!-- llista de pel·licula -->
<!ELEMENT llista_pelicules (pelicula+)>
<!ELEMENT pelicula (titol, director, any, actors)>
<!ATTLIST pelicula id ID #REQUIRED>
<!ELEMENT titol (#PCDATA)>
<!ATTLIST titol idioma CDATA #REQUIRED>
<!ELEMENT director (#PCDATA)>
<!ELEMENT any (#PCDATA)>
<!ELEMENT actors (actor_ref+)>
<!ELEMENT actor_ref EMPTY>
<!-- Referencia de les IDs dels actors -->
<!ATTLIST actor_ref ref IDREF #REQUIRED>

<!-- llista de recomanacions de pel·licules -->
<!ELEMENT llista_recomanacions_pelicules (recomanacio*)>
<!ELEMENT recomanacio EMPTY>
<!-- Referencia de les IDs de les pel·licules -->
<!ATTLIST recomanacio ref IDREF #REQUIRED>

=== 2526dustinpicon-hash/LMSGI_DTD/dtd2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cataleg SYSTEM "dtd2.dtd">

<cataleg>
    <llista_actors>
        <actor id="A1">
            <nom>Juan</nom>
            <edat>40</edat>
        </actor>
        <actor id="A2">
            <nom>Carlos</nom>
            <edat>50</edat>
        </actor>
        <actor id="A3">
            <nom>Roberto</nom>
            <edat>60</edat>
        </actor>
    </llista_actors>
    <llista_pelicules>
        <pelicula id="B1">
            <titol idioma="EN">Titanic</titol>
            <director>James Cameron</director>
            <any>1997</any>
            <actors>
                <actor_ref ref="A1"/>
                <actor_ref ref="A2"/>
            </actors>
        </pelicula>
        <pelicula id="B2">
            <titol idioma="EN">Transformers</titol>
            <director>Michael Bay</director>
            <any>2007</any>
            <actors>
                <actor_ref ref="A1"/>
            </actors>
        </pelicula>
        <pelicula id="B3">
            <titol idioma="EN">Fight Club</titol>
            <director>David Fincher</director>
            <any>1999</any>
            <actors>
                <actor_ref ref="A3"/>
            </actors>
        </pelicula>
    </llista_pelicules>
    <llista_recomanacions_pelicules>
        <recomanacio ref="B1"/>
        <recomanacio ref="B2"/>
        <recomanacio ref="B3"/>
    </llista_recomanacions_pelicules>
</cataleg>
